export { default as HomePage } from '~/pages/home'
export { default as HospitalPage } from '~/pages/hospital'
export { default as NewsPage } from '~/pages/news'
export { default as AboutPage } from '~/pages/about'
export { default as NotFoundPage } from '~/pages/not-found'
